services:
  backend:
    build: ./backend
    networks:
      - bridge
  proxy:
    build: ./proxy
    ports: 
      - 8080:80
    networks:
      - bridge
networks:
  default:
  bridge:
    driver: bridge